### ISSUE TITLE
Retrofit out all jQuery based JavaScript for vanilla ES6

### ISSUE THREAD

**Issue by davebeesley** [hankchizljaw/stalfos#25]
Because, you know, we ain't kids anymore ;)

**Comment by Andy-set-studio** [comment]
Hey, I almost felt your neckbeard from here! 😉

I do agree though, vanilla JS should be the baseline of Stalfos: not jQuery. While we're at it, we should definitely introduce ES6 to the mix. 

At the moment, there's a block. I'm reworking the gulp setup on the **develop** branch which is needed for any integration of browserify, babel etc.

I'm hoping to get this done and released within the next couple of weeks though.

I'll map out a project in the interim. Fancy getting involved in the work?

**Comment by Andy-set-studio** [comment]
[A skeletal project structure](https://github.com/hankchizljaw/stalfos/projects/1) for when this is ready to go. We'll probably want to make each item a separate issue to aid discussion and proper specification.

**Comment by Andy-set-studio** [comment]
Removing block because [v1.1.0](https://github.com/hankchizljaw/stalfos/releases/tag/v1.1.0) has been released 🎉

**Comment by davebeesley** [comment]
So are we good to go with ES6.
Forks repo, cracks knuckles, grabs a beer, goes and watches TV ;)

**Comment by Andy-set-studio** [comment]
We are indeed. I'm otherwise occupied at the moment, but will happily take a PR! 

The [hankchizljaw.io](https://github.com/hankchizljaw/hankchizljaw.io) repo has a rough cut of what I was thinking, so could be used as a base.

**Comment by davebeesley** [comment]
Pull Request added - https://github.com/hankchizljaw/stalfos/pull/27

**Comment by Andy-set-studio** [comment]
🧹Closing this issue because a complete rebuild for V2 is on the way 🧹
