### ISSUE TITLE
Fanmail & question

### ISSUE THREAD

**Issue by alolalo** [hankchizljaw/stalfos#30]
Hi Andy 🖖,

I've been using Hylia to create my blog www.guus.rocks, and I'm a huge fan of the whole work. As a designer who can code but is simply to inexperienced to understand all the nuts and bolts of package management, it's a life-saver!

I'm a free-lance ux/ui-designer from Amsterdam that can code (not program, code) and that wants to become a front-end designer, and I would love to help out on an open-source project with a dev that inspires me (you do!) so I can learn how you designed, structured & built your code. 

I built my own utility-first design system in Sketch that integrates with Tailwind, but I want to take that a step further and build my own utility-first framework that can do all the things you can't do in Sketch. I'm at that border and I need to cross it.

I'm in a stage of my life where I want to develop skills from the ground-up and fix all solutions from below, not above. So I would love to learn to build a utility-first system it from scratch, fixing it for myself first, and **That** is exactly why I would like to learn from you as you are doing so right now and maybe you are interested to having somebody join the project who has the same idea but a different take on it.

Therefore I would like to ask you; **would you like to be my mentor** and have a designer contribute to your project by creating the visual side (logo, icon-set, infographics) of Stalfos, in exchange to help him learn the ropes of designing and creating a utility-first ds? 

And please, feel free to say no as I totally understand that, being a free-lancer myself, you simply don't have the time or energy after fixing your own sh*% 🖖

Greetings,
Guus

**Comment by Andy-set-studio** [comment]
Hey there! 

First of all, thank you for the kind words. They mean a lot.

I'm afraid I won't be able to mentor you. I’ve already got my hands full with a couple of other folks! I’ve also hired a designer to help out with some branding on this project too.

I really wish you all the best for the future. I'm sure you're going to do great!
